### ISSUE TITLE
Add HD assets support for custom texture patches.

### ISSUE THREAD

**Issue by mikote111** [AntonioDePau/KHPCPatchManager#23] opened 2022-01-23 02:25 UTC
**Describe the bug**
When trying to use HD assets on a model with custom texture patches the game crashes, or when the game is supposed to do that animation, the whole texture turns gray. 

**Version used (please complete the following information):**
v1.14

**Additional context**
I did a custom model replacing kh2 sora and I wanted to use texture patches to have an animated face, but the texture is not the same as sora's so I had to do some adjustments to the texture patches (size and position), the remastered assets work with no problems, but when one texture patch is supposed to replace one part of the texture it turns it all gray or the game crashes. Everything works perfectly if i do not use HD assets.

**Comment by AntonioDePau** [comment] 2022-02-20 16:18
Hey, can you confirm that this happens for MDLX files?
Do you mind sharing your custom MDLX file (send it to me privately on Discord if your prefer: AntonioDePau@6333)?

**Comment by mikote111** [comment] 2022-02-20 17:27
Yeah, it happens with MDLX files. I added you on discord.

**Comment by AntonioDePau** [comment] 2022-03-05 18:55
Closing this now as it was caused by a mix of:
- DDS files with mipmaps (shouldn't have that for KH PC)
- Incorrect texture size for eyes (needs to be the original texture width and height times 2)
- Incorrect texture order (the DDS files need to match the order of the SD textures)

**Closed by AntonioDePau** 2022-03-05 18:55 UTC
